import { C, CP } from '../constants';

function _mr(fields) {
  const r = new Array(31).fill('');
  Object.entries(fields).forEach(([k, v]) => { if (C[k] !== undefined) r[C[k]] = v; });
  return r;
}

function _mp(fields) {
  const r = new Array(18).fill('');
  Object.entries(fields).forEach(([k, v]) => { if (CP[k] !== undefined) r[CP[k]] = v; });
  return r;
}

export const MOCK_TUTOR_ROWS = [
  _mr({APP_ID:'KB-001',SUBMITTED:'29/09/2026 09:15:00',EMAIL:'rahul.sharma@gmail.com',NAME:'Rahul Sharma',PHONE:'9876543210',STUDENT:'Working',COLLEGE:'Tech Mahindra, Hyd',LOCATION:'Gachibowli',TRAVEL:'Bike',CLASSES:'0-5, 6-8',SUBJECTS:'Maths, Science (bio,chem,phy)',LANGUAGES:'English, Telugu',EXTRAS:'Computer basics',TIMINGS:'Between 5am to 10am',PAY:'500-1000',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'9:00-6:00',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:'',RATING:''}),
  _mr({APP_ID:'KB-002',SUBMITTED:'28/09/2026 14:30:00',EMAIL:'priya.kumari@gmail.com',NAME:'Priya Kumari',PHONE:'8374644508',STUDENT:'Student',COLLEGE:'Osmania University',LOCATION:'Chaitanyapuri',TRAVEL:'Bus',CLASSES:'0-5, 6-8',SUBJECTS:'Maths, Science (bio,chem,phy)',LANGUAGES:'Hindi, English, Telugu',EXTRAS:'Communication skills, Computer basics',TIMINGS:'Between 5am to 10am',PAY:'400-800',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'9:00-4:00',CONTACTED:'Yes',NOTES:'Very enthusiastic, follow up this week',MAIL_SENT:'Yes',INTERVIEW_STATUS:'Scheduled',INTERVIEW_AT:'05/10/2026 11:00:00'}),
  _mr({APP_ID:'KB-003',SUBMITTED:'27/09/2026 11:20:00',EMAIL:'arun.nair@gmail.com',NAME:'Arun Nair',PHONE:'9988776655',STUDENT:'Working',COLLEGE:'Infosys, Hyderabad',LOCATION:'HITEC City',TRAVEL:'Own vehicle',CLASSES:'6-8, 8-10',SUBJECTS:'Maths, Social',LANGUAGES:'English, Malayalam, Telugu',EXTRAS:'Abacus',TIMINGS:'Between 6pm to 9pm',PAY:'600-1200',REFERRAL:'Nikhil Kumar',OPEN:'No',WORKHOURS:'9:00-5:00',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
  _mr({APP_ID:'KB-004',SUBMITTED:'26/09/2026 16:45:00',EMAIL:'sunita.reddy@gmail.com',NAME:'Sunita Reddy',PHONE:'7654321098',STUDENT:'Student',COLLEGE:'JNTU Hyderabad',LOCATION:'Kukatpally',TRAVEL:'Public transport',CLASSES:'0-5',SUBJECTS:'Science (bio,chem,phy), Social',LANGUAGES:'Telugu, English',EXTRAS:'Drawing, Craft',TIMINGS:'Between 4pm to 8pm',PAY:'300-600',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'',CONTACTED:'Yes',NOTES:'Prefers morning slots only',MAIL_SENT:'No',INTERVIEW_STATUS:'Cleared'}),
  _mr({APP_ID:'KB-005',SUBMITTED:'25/09/2026 08:00:00',EMAIL:'vikram.patel@gmail.com',NAME:'Vikram Patel',PHONE:'9123456780',STUDENT:'Working',COLLEGE:'TCS, Hyderabad',LOCATION:'Secunderabad',TRAVEL:'Bike',CLASSES:'8-10, 10-12',SUBJECTS:'Maths',LANGUAGES:'Hindi, English, Marathi',EXTRAS:'Vedic Maths',TIMINGS:'Between 6am to 9am',PAY:'800-1500',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'9:30-6:30',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
  _mr({APP_ID:'KB-006',SUBMITTED:'24/09/2026 13:10:00',EMAIL:'deepa.v@gmail.com',NAME:'Deepa V',PHONE:'8765432109',STUDENT:'Student',COLLEGE:'University of Hyderabad',LOCATION:'Gachibowli',TRAVEL:'Public transport',CLASSES:'0-5, 6-8',SUBJECTS:'Maths, Science (bio,chem,phy), Social',LANGUAGES:'Telugu, English, Kannada',EXTRAS:'Yoga, Music',TIMINGS:'Between 3pm to 7pm',PAY:'350-700',REFERRAL:'Priya Kumari',OPEN:'Yes',WORKHOURS:'',CONTACTED:'Yes',MAIL_SENT:'Yes',LAST_CALLED:'28/09/2026 10:30:00',INTERVIEW_STATUS:'Rejected'}),
  _mr({APP_ID:'KB-007',SUBMITTED:'23/09/2026 10:55:00',EMAIL:'arjun.mehta@gmail.com',NAME:'Arjun Mehta',PHONE:'9012345678',STUDENT:'Working',COLLEGE:'Wipro, Hyderabad',LOCATION:'Madhapur',TRAVEL:'Own vehicle',CLASSES:'6-8, 8-10',SUBJECTS:'Maths, Science (bio,chem,phy)',LANGUAGES:'Hindi, English, Gujarati',EXTRAS:'Coding, Robotics',TIMINGS:'Between 7am to 10am',PAY:'700-1300',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'10:00-7:00',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
  _mr({APP_ID:'KB-008',SUBMITTED:'22/09/2026 17:30:00',EMAIL:'ananya.singh@gmail.com',NAME:'Ananya Singh',PHONE:'8901234567',STUDENT:'Student',COLLEGE:'Hyderabad Central University',LOCATION:'Tarnaka',TRAVEL:'Bus',CLASSES:'0-5',SUBJECTS:'Science (bio,chem,phy), Social, Other',LANGUAGES:'Hindi, English, Bengali',EXTRAS:'Dance, Art',TIMINGS:'Between 4pm to 9pm',PAY:'300-500',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
  _mr({APP_ID:'KB-009',SUBMITTED:'21/09/2026 09:45:00',EMAIL:'karthik.m@gmail.com',NAME:'Karthik M',PHONE:'7890123456',STUDENT:'Working',COLLEGE:'Accenture, Hyderabad',LOCATION:'Banjara Hills',TRAVEL:'Bike',CLASSES:'8-10, 10-12',SUBJECTS:'Maths, Science (bio,chem,phy)',LANGUAGES:'Tamil, English, Telugu',EXTRAS:'Chess, Rubiks cube',TIMINGS:'Between 5am to 9am',PAY:'900-1600',REFERRAL:'No',OPEN:'No',WORKHOURS:'9:00-6:00',CONTACTED:'Yes',NOTES:'Only available on weekends',MAIL_SENT:'Yes',LAST_CALLED:'25/09/2026 14:00:00',INTERVIEW_STATUS:'Scheduled',INTERVIEW_AT:'07/10/2026 09:00:00'}),
  _mr({APP_ID:'KB-010',SUBMITTED:'20/09/2026 12:20:00',EMAIL:'divya.krishna@gmail.com',NAME:'Divya Krishna',PHONE:'6789012345',STUDENT:'Student',COLLEGE:'BITS Pilani (Hyd campus)',LOCATION:'Shameerpet',TRAVEL:'Own vehicle',CLASSES:'6-8, 8-10, 10-12',SUBJECTS:'Maths',LANGUAGES:'Telugu, English, Tamil',EXTRAS:'IIT coaching experience',TIMINGS:'Between 5pm to 9pm',PAY:'1000-2000',REFERRAL:'Karthik M',OPEN:'Yes',WORKHOURS:'',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
  _mr({APP_ID:'KB-011',SUBMITTED:'19/09/2026 15:00:00',EMAIL:'rohit.jain@gmail.com',NAME:'Rohit Jain',PHONE:'5678901234',STUDENT:'Working',COLLEGE:'HCL Technologies',LOCATION:'Kondapur',TRAVEL:'Bike',CLASSES:'0-5, 6-8',SUBJECTS:'Maths, Other',LANGUAGES:'Hindi, English, Rajasthani',EXTRAS:'Abacus, Mental maths',TIMINGS:'Between 6am to 9am, 6pm to 9pm',PAY:'500-900',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'9:00-5:30',CONTACTED:'No',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
  _mr({APP_ID:'KB-012',SUBMITTED:'18/09/2026 07:30:00',EMAIL:'meera.nambiar@gmail.com',NAME:'Meera Nambiar',PHONE:'4567890123',STUDENT:'Student',COLLEGE:'St Francis College',LOCATION:'Begumpet',TRAVEL:'Public transport',CLASSES:'0-5',SUBJECTS:'Science (bio,chem,phy), Social',LANGUAGES:'Malayalam, English, Hindi',EXTRAS:'Story telling, Phonics',TIMINGS:'Between 3pm to 7pm',PAY:'250-500',REFERRAL:'No',OPEN:'Yes',WORKHOURS:'',CONTACTED:'Yes',MAIL_SENT:'No',INTERVIEW_STATUS:''}),
];

export const MOCK_PARENT_ROWS = [
  _mp({PARENT_ID:'P-001',ONBOARDED_ON:'29/09/2026 08:00:00',NAME:'Ramesh Gupta',PHONE:'9111222333',EMAIL:'ramesh.gupta@gmail.com',LOCATION:'Gachibowli',ADDRESS:'Flat 4B, Srinivas Apt, Gachibowli',STUDENT_NAME:'Riya Gupta',STUDENT_GRADE:'Grade 5',SUBJECTS_NEEDED:'Maths, Science (bio,chem,phy)',ASSIGNED_TUTOR:'',CONTACTED:'No',NOTES:'',MAILED:'No'}),
  _mp({PARENT_ID:'P-002',ONBOARDED_ON:'28/09/2026 10:30:00',NAME:'Lakshmi Devi',PHONE:'9222333444',EMAIL:'lakshmi.devi@gmail.com',LOCATION:'Chaitanyapuri',ADDRESS:'House 12, MIG Colony, Chaitanyapuri',STUDENT_NAME:'Aditya Kumar',STUDENT_GRADE:'Grade 8',SUBJECTS_NEEDED:'Maths, Social',ASSIGNED_TUTOR:'Priya Kumari',LAST_CONTACTED:'29/09/2026 14:00:00',CONTACTED:'Yes',NOTES:'Prefers female tutor',MAILED:'Yes'}),
  _mp({PARENT_ID:'P-003',ONBOARDED_ON:'27/09/2026 16:00:00',NAME:'Suresh Rao',PHONE:'9333444555',EMAIL:'suresh.rao@gmail.com',LOCATION:'HITEC City',ADDRESS:'102 Skyline Towers, HITEC City',STUDENT_NAME:'Pooja Rao',STUDENT_GRADE:'Grade 3',SUBJECTS_NEEDED:'Maths, Science (bio,chem,phy), Social',ASSIGNED_TUTOR:'',CONTACTED:'No',NOTES:'',MAILED:'No'}),
  _mp({PARENT_ID:'P-004',ONBOARDED_ON:'26/09/2026 09:15:00',NAME:'Anjali Sharma',PHONE:'9444555666',EMAIL:'anjali.sharma@gmail.com',LOCATION:'Kukatpally',ADDRESS:'3-45, KPHB Phase 3, Kukatpally',STUDENT_NAME:'Dev Sharma',STUDENT_GRADE:'Grade 10',SUBJECTS_NEEDED:'Maths',ASSIGNED_TUTOR:'',CONTACTED:'No',NOTES:'Urgent — board exams in April',MAILED:'No'}),
  _mp({PARENT_ID:'P-005',ONBOARDED_ON:'25/09/2026 11:45:00',NAME:'Venkat Reddy',PHONE:'9555666777',EMAIL:'venkat.reddy@gmail.com',LOCATION:'Banjara Hills',ADDRESS:'Plot 7, Road No 10, Banjara Hills',STUDENT_NAME:'Arjun Reddy',STUDENT_GRADE:'Grade 7',SUBJECTS_NEEDED:'Science (bio,chem,phy), Other',ASSIGNED_TUTOR:'Karthik M',LAST_CONTACTED:'27/09/2026 10:00:00',CONTACTED:'Yes',NOTES:'',MAILED:'Yes'}),
  _mp({PARENT_ID:'P-006',ONBOARDED_ON:'24/09/2026 14:20:00',NAME:'Sujatha Iyer',PHONE:'9666777888',EMAIL:'sujatha.iyer@gmail.com',LOCATION:'Madhapur',ADDRESS:'Flat 201, Prestige Apts, Madhapur',STUDENT_NAME:'Kavya Iyer',STUDENT_GRADE:'Grade 6',SUBJECTS_NEEDED:'Maths, Social',ASSIGNED_TUTOR:'',CONTACTED:'No',NOTES:'',MAILED:'No'}),
  _mp({PARENT_ID:'P-007',ONBOARDED_ON:'23/09/2026 07:30:00',NAME:'Praveen Kumar',PHONE:'9777888999',EMAIL:'praveen.k@gmail.com',LOCATION:'Secunderabad',ADDRESS:'HIG 34, Defence Colony, Secunderabad',STUDENT_NAME:'Manya Kumar',STUDENT_GRADE:'Grade 4',SUBJECTS_NEEDED:'Maths, Science (bio,chem,phy), Social',ASSIGNED_TUTOR:'',CONTACTED:'No',NOTES:'',MAILED:'No'}),
  _mp({PARENT_ID:'P-008',ONBOARDED_ON:'22/09/2026 17:00:00',NAME:'Meghana Pillai',PHONE:'9888999000',EMAIL:'meghana.p@gmail.com',LOCATION:'Tarnaka',ADDRESS:'Flat 5C, Nakshatra Apts, Tarnaka',STUDENT_NAME:'Sai Pillai',STUDENT_GRADE:'Grade 9',SUBJECTS_NEEDED:'Maths, Other',ASSIGNED_TUTOR:'',CONTACTED:'No',NOTES:'Wants tutor with IIT experience',MAILED:'No'}),
];
